### ISSUE TITLE
message box can't show language like japanese,korean....

### ISSUE THREAD

**Issue by secondroms** [rpgboss/rpgboss#245]
i import korean/japanese fonts and try it. but didn't show.

**Comment by tommycli** [comment]
Fixed in fc28149ad3fe71ef28c81e15c0b4577cb0e4178e.

However, user must specify all the non-ASCII characters they plan on using in a special box in Database->Startup. This sucks, but libgdx must generate a BitmapFont out of a fixed set of characters.

See caveats section here for details: https://github.com/libgdx/libgdx/wiki/Gdx-freetype

![snapshot18](https://cloud.githubusercontent.com/assets/157358/5996531/35bccdae-aa60-11e4-837a-343b96ec5ce9.png)

**Comment by tommycli** [comment]
There may be a way to do this without requiring the user to pre-input all their Unicode characters in that field. Perhaps by scanning the corpus of dialogue / text on game load.

Let me know if this is a problem. I heard Asian languages have thousands of glyphs.

**Comment by secondroms** [comment]
yes, some asian language have 1,000~10,000 characters likes my county, korea. japanese can work well, but korea and china still had problem.

**Comment by tommycli** [comment]
Alright, well hopefully that last patch fixes it. It should be in the next release.
