### ISSUE TITLE
Can games be sold?

### ISSUE THREAD

**Issue by RealAquilus** [rpgboss/rpgboss#483]
Can we sell our games? And we need obbligatory to release the source code of our game? And can we change the icon of our game with Resource Hacker for example?

**Comment by henriquelalves** [comment]
Well, no one answered this yet, and I'm kinda new to RPGBoss, but I guess you can sell your game as long as you release it under AGPL along with its source-code.
I may be wrong, though; I'm not sure if AGPL extends only to modifications of the Engine itself. But since the game made with RPGBoss is a product of the engine, I guess the License is also applicable to it.
